FROM node:24.16

ENV CI=true

RUN npm install -g pnpm

WORKDIR /app

COPY package.json pnpm-lock.yaml* pnpm-workspace.yaml* ./

RUN pnpm install

COPY . .

EXPOSE 4321

# Ejecutar en modo desarrollo
CMD ["pnpm", "exec", "astro", "dev", "--host", "0.0.0.0"]